### ISSUE TITLE
Need to catch request errors before calling pipe.

### ISSUE THREAD

**Issue by Parakleta** [hughsk/npm-offline#4]
As it stands npm-proxy crashes with an uncaught exception if you try to retrieve a package it cannot find and you are actually offline.  It should be more robust than this.

Fixing this problem is just a matter of adding an `.on('error', handle)` between the call to `request` and `.pipe()` on [Line 41 in index.js](https://github.com/hughsk/npm-offline/blob/a762d675447ab3f97fa0e8952fd47aabcd6aa897/index.js#L41).

**Comment by hughsk** [comment]
Ok, could you send through a pull request to fix this?

**Comment by Parakleta** [comment]
No.  I took the time to diagnose the issue but I cannot spare any more.

**Comment by hughsk** [comment]
Neither can I, sorry.

**Comment by Parakleta** [comment]
I'm not sure it's particularly honest to close an issue just because you don't have the time to fix it.  The issue still exists.
